version: '3.8'

services:
  core:
    build: ./docteurmemo
    command: gunicorn docteurmemo.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  prediction:
    build: ./docteurmemo_prediction
    command: gunicorn docteurmemo_prediction.wsgi:application --bind 0.0.0.0:8001
    ports:
      - 8001:8001
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
volumes:
  postgres_data:
