# Generated by Django 4.2.7 on 2023-12-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
